import requests


def request(URL) -> None:
	print(URL)

	auth = {"Authorization": "Bearer Hello"}
	response = requests.get(URL, headers=auth)
	print(response)
	print(response.json())

	print("——————————————————————————————")


request("http://localhost:8081/api")
request("http://localhost:8081/api/group")
request("http://localhost:8081/api/group/all")
request("http://localhost:8081/api/group/id")
request("http://localhost:8081/api/group/id/1")
request("http://localhost:8081/api/group/id/100")
request("http://localhost:8081/api/group/label")
request("http://localhost:8081/api/group/label/Smart")
request("http://localhost:8081/api/group/label/TestyMcTestface")
request("http://localhost:8081/api/network")
request("http://localhost:8081/api/networks/all")
request("http://localhost:8081/api/network")
request("http://localhost:8081/api/networks/1")
request("http://localhost:8081/api/networks/100")
request("http://localhost:8081/api/networks/1/device")
request("http://localhost:8081/api/networks/1/devices/address")
request("http://localhost:8081/api/networks/1/devices/address/192.168.1.21")
request("http://localhost:8081/api/networks/1/devices/address/192.168.1.211")
request("http://localhost:8081/api/networks/1/devices/address/192.168.1.512")
request("http://localhost:8081/api/networks/1/devices/id")
request("http://localhost:8081/api/networks/1/devices/id/1")
request("http://localhost:8081/api/networks/1/devices/id/1000")
request("http://localhost:8081/api/networks/1/devices/label")
request("http://localhost:8081/api/networks/1/devices/label/Bedroom-Curtain")
request("http://localhost:8081/api/networks/1/devices/label/TestyMcTestface")
request("http://localhost:8081/api/networks/1/devices")
request("http://localhost:8081/api/networks/1/devices/all")
request("http://localhost:8081/api/networks/1/devices/group")
request("http://localhost:8081/api/networks/1/devices/group/id")
request("http://localhost:8081/api/networks/1/devices/group/id/1")
request("http://localhost:8081/api/networks/1/devices/group/id/100")
request("http://localhost:8081/api/networks/1/devices/group/label")
request("http://localhost:8081/api/networks/1/devices/group/label/Smart")
request("http://localhost:8081/api/networks/1/devices/group/label/TestyMcTestface")
request("http://localhost:8081/api/networks/label")
request("http://localhost:8081/api/networks/label/Home")
request("http://localhost:8081/api/networks/label/TestyMcTestface")
request("http://localhost:8081/api/networks/label/Home/device")
request("http://localhost:8081/api/networks/label/Home/devices/address")
request("http://localhost:8081/api/networks/label/Home/devices/address/192.168.1.21")
request("http://localhost:8081/api/networks/label/Home/devices/address/192.168.1.211")
request("http://localhost:8081/api/networks/label/Home/devices/address/192.168.1.512")
request("http://localhost:8081/api/networks/label/Home/devices/id")
request("http://localhost:8081/api/networks/label/Home/devices/id/1")
request("http://localhost:8081/api/networks/label/Home/devices/id/1000")
request("http://localhost:8081/api/networks/label/Home/devices/label")
request("http://localhost:8081/api/networks/label/Home/devices/label/Bedroom-Curtain")
request("http://localhost:8081/api/networks/label/Home/devices/label/TestyMcTestface")
request("http://localhost:8081/api/networks/label/Home/devices")
request("http://localhost:8081/api/networks/label/Home/devices/all")
request("http://localhost:8081/api/networks/label/Home/devices/group")
request("http://localhost:8081/api/networks/label/Home/devices/group/id")
request("http://localhost:8081/api/networks/label/Home/devices/group/id/1")
request("http://localhost:8081/api/networks/label/Home/devices/group/id/100")
request("http://localhost:8081/api/networks/label/Home/devices/group/label")
request("http://localhost:8081/api/networks/label/Home/devices/group/label/Smart")
request("http://localhost:8081/api/networks/label/Home/devices/group/label/TestyMcTestface")
